# Copyright (c) 2018, Red Hat, Inc.
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

# -----------------------------------------------------------------------------
# SET REPOSITORIES
#

- set_fact: storage_cl_try_osp="{{ ansible_distribution == 'Red Hat Enterprise Linux' and ansible_distribution_major_version == 7 }}"

- name: Disable unwanted OSP repositories on RHEL
  yum_repository:
    name: "rhel-{{ ansible_distribution_major_version}}-server-openstack-{{ item }}.0-rpms"
    state: absent
  ignore_errors: True
  when: storage_cl_try_osp
  loop: "{{ range(5, 14)|list }}"

- name: Enable OSP repository on RHEL
  yum_repository:
    name: "rhel-{{ ansible_distribution_major_version}}-server-openstack-14.0-rpms"
    state: present
  register: enabled_osp
  ignore_errors: True
  when: storage_cl_try_osp

- name: Enable required packages for RDO on RHEL
  yum_repository:
    name: "{{ item }}"
    state: present
  when: not enabled_osp
  with_list:
      - rhel-7-server-optional-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-rh-common-rpms

- name: Install RDO repository on RHEL and Fedora
  package:
    name: https://repos.fedorapeople.org/repos/openstack/openstack-stein/rdo-release-stein-2.noarch.rpm
    state: present
  when: (storage_cl_try_osp and not enabled_osp) or ansible_distribution == "Fedora"

- name: Install RDO respository on CentOS
  package:
    name: centos-release-openstack-pike
    state: present
  when: ansible_distribution == "CentOS"
