- name: Set repositories
  include_tasks: setup_openstack_repos.yml

# -----------------------------------------------------------------------------
# INSTALL CINDERCLIENT
#

- name: Install cinderclient package
  package:
    name: python2-cinderclient
    state: present
