- name: Set repositories
  include_tasks: setup_openstack_repos.yml
  become: true

# -----------------------------------------------------------------------------
# INSTALL CINDER AND CINDERLIB
#

- name: Install Cinder package
  package:
    # We cannot use python-cinder because that doesn't set cinder-rtstool
    name: openstack-cinder
    state: present

- name: Install Cinderlib package from URL
  package:
    name: python2-cinderlib
    state: present
  when: not enabled_osp

- name: Install Cinderlib package from URL
  yum:
    # Install from RDO's URL. We can do it because the spec has
    # "Requires: openstack-cinder >= 12.0.0"
    name: http://mirror.centos.org/centos/7/cloud/x86_64/openstack-stein/python2-cinderlib-0.9.0-1.el7.noarch.rpm
    state: present
  when: enabled_osp


# -----------------------------------------------------------------------------
# INSTALL VENDOR SPECIFIC DEPENDENCIES
#

- name: Install and setup driver specific dependencies
  include_tasks: setup_cinderlib_driver_dependencies.yml
  vars:
    driver: "{{ backend.volume_driver | mandatory }}"
  with_list: "{{ storage_backends.values() | list | mandatory }}"
  loop_control:
    loop_var: backend
